### ISSUE TITLE
DEBUG:Evtx.Evtx:Record at 0x....

### ISSUE THREAD

**Issue by JLT032** [williballenthin/process-forest#14]
Dear,

With the minute patch in place where a b is inserted on line 25 i now run into unexpected output.

INFO:process-forest.global:using evtx log file
DEBUG:Evtx.Evtx:FILE HEADER at 0x0.
DEBUG:Evtx.Evtx:CHUNK HEADER at 0x1000.
DEBUG:Evtx.Evtx:Record at 0x1200.
DEBUG:Evtx.Evtx:Record at 0x1c10.
DEBUG:Evtx.Evtx:Record at 0x20b8.
DEBUG:Evtx.Evtx:Record at 0x2370.
DEBUG:Evtx.Evtx:Record at 0x2a80.
....
DEBUG:Evtx.Evtx:Record at 0x10fc8.
DEBUG:Evtx.Evtx:CHUNK HEADER at 0x11000.
DEBUG:Evtx.Evtx:Record at 0x11200.
.....

this with the latest master version of process-forest

**Comment by williballenthin** [comment]
these are debug messages that are written to STDERR to show the progress of processing. You can safely redirect this output to `/dev/null` or otherwise ignore it.
