### ISSUE TITLE
Add setup.py

### ISSUE THREAD

**Issue by ekristen** [williballenthin/process-forest#2]
It would be nice to see a setup.py and possible see this published to the python package repo. At the very least it would make it install-able via pip using git+ssh. 

Thanks.

**Comment by williballenthin** [comment]
Good idea! Want to take a shot dev'ing the `setup.py` file? For testing, you can use `pip install -e /path/to/directory/containing/setup.py`. I'll be happy to upload the package to PyPI.

**Comment by ekristen** [comment]
It would be nice to see you add `setup.py` to all your repos :) Thanks.

**Comment by williballenthin** [comment]
Noted. I typically add features to my projects when I come across a
personal need, so I'll add them when that happens. In the mean time, I
always accept and appreciate submissions from other users.

**Comment by ekristen** [comment]
We'd like to add all your scripts to the SIFT workstation. I don't mind doing 1 or 2 PR's if needed, but it would be nice if you could do it to them so people can more readily install and use your tools, plus we can add it to the build and update script of SIFT and get your updates added automatically.

I'll see about doing one on this repo.

**Comment by PoorBillionaire** [comment]
#4

**Comment by williballenthin** [comment]
closed in 828bf53e5a5e02056db58fa9eab5b34c21669528
